version: '3.7'

services:
  am.services.portfolio.api:
    image: ${DOCKER_REGISTRY-}am.portfolio.api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: portfolio_api
    build:
      context: .
      dockerfile: services/portfolio/api/Dockerfile
    ports:
      - 1002:1002
    environment:
      - ASPNETCORE_URLS=http://+:1002
      - DatabaseConnections__PostgreSQL__Password=${POSTGRES_PASSWORD}
      - DatabaseConnections__MongoDB__Password=${MONGO_PASSWORD}
  am.services.portfolio.worker:
    image: ${DOCKER_REGISTRY-}am.portfolio.worker:${PLATFORM:-linux}-${TAG:-latest}
    container_name: portfolio_worker
    build:
      context: .
      dockerfile: services/portfolio/worker/Dockerfile
    environment:
      - DatabaseConnections__PostgreSQL__Password=${POSTGRES_PASSWORD}
      - DatabaseConnections__MongoDB__Password=${MONGO_PASSWORD}